spring.application.name=TrendHive
server.error.include-message:always
Spring.datasource.url=jdbc:mysql://localhost:3306/TrendHive
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
Spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.servlet.multipart.max-request-size=10MB
razorpay.keyId=your razorpay key id credentials
razorpay.keySecret=your razorpay keySecret credentials
razorpay.currency=INR
razorpay.companyName=TrendHive
#System.out.println("Razorpay Key: " + keyId);
spring.security.user.name=your user name
spring.security.user.password=your user password
