spring.application.name=TrendHive
server.error.include-message:always
Spring.datasource.url=jdbc:mysql://localhost:3306/TrendHive
spring.datasource.username=root
spring.datasource.password=Bhushan@9854
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
Spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.servlet.multipart.max-request-size=10MB
razorpay.keyId=rzp_test_GVsB0C5GXJShcd
razorpay.keySecret=kIMeV5nvmnY6dIAxhVXX2ctI
razorpay.currency=INR
razorpay.companyName=TrendHive
#System.out.println("Razorpay Key: " + keyId);
spring.security.user.name=bhushan
spring.security.user.password=bhushan1234
